### ISSUE TITLE
Is it compatible with windows ?

### ISSUE THREAD

**Issue by miranos** [tklauser/libtar#2]
Hi
Is there a way to make the code works for windows ?

**Comment by tklauser** [comment]
This is a maintainance repo for the original libtar code. I do not intend to add any additional code besides bug and security fixes. If you want to make libtar work on Windows, feel free to fork and try it out...

**Comment by kuhlmannmarkus** [comment]
@miranos Have you been successful here? I would also like to use libtar on Windows.
