### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by egpbos** [tklauser/libtar#4]
Hi @tklauser, I am building a conda-forge package for libtar. Would you like to be added as a maintainer? Or would you know of others who would like to be added?

**Comment by egpbos** [comment]
Also, I'm wondering whether the COPYRIGHT text was taken from some existing license. It seems to be a combination of MIT (1st paragraph) and BSD 3-clause. On conda-forge, recipes should mention which license the packages are distributed under. I have now listed it as BSD 3-clause.

**Comment by tklauser** [comment]
Hi @egpbos. This repo is mainly a collection of additional patches on top of the maintainance repo at https://repo.or.cz/libtar.git (mainly taken from the libtar Debian package).

As I'm not the original author of libtar (or its COPYRIGHT file for that matter), but I'd say listing it as BSD 3-clause is fine.

As I do use conda-forge myself, I'd prefer not to to be listed as a maintainer (of the conda recipe) there, but somehow linking this repo is of course fine.

Thanks

**Comment by egpbos** [comment]
Thanks!

**Comment by egpbos** [comment]
Just for future reference, it seems like the license text is actually this one: https://opensource.org/licenses/NCSA, so a standard license after all, albeit a less used one :)
